//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWOT.Del {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWOT.Del.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ձեր բիզնեսի ո՞ր հատկանիշներն ունեն առավելություններ մրցակիցների համեմատ։.
        /// </summary>
        internal static string _1_ {
            get {
                return ResourceManager.GetString("1.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ի՞նչն եք դուք ավելի լավ անումքան Ձեր մրցակիցները։.
        /// </summary>
        internal static string _2_ {
            get {
                return ResourceManager.GetString("2.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ի՞նչ ռեսուրսներ ունեք դուք, որոնք օգնում են մրցակիցներից առաջ անցնել։.
        /// </summary>
        internal static string _3_ {
            get {
                return ResourceManager.GetString("3.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Որո՞նք են Ձեր ուժեղ կողմերը Ձեր մրցակիցների տեսանկյունից։.
        /// </summary>
        internal static string _4_ {
            get {
                return ResourceManager.GetString("4.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Որո՞նք են ընկերության այն եզակի ակտիվները, որոնք Ձեզ առավելություն են տալիս։.
        /// </summary>
        internal static string _5_ {
            get {
                return ResourceManager.GetString("5.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	Ո՞ր արտաքին գործոններն են բացասական ազդեցություն թողնում Ձեր բիզնեսի վրա։
        ///2.	Արդյո՞ք դուք տեղյակ եք շուկայի այն զարգացումների մասին, որոնք կարող եք օգտագործել Ձեր օգտին։
        ///3.	Կա՞ն արդյոք օրենսդրական փոփոխություններ, որոնցից Ձեր բիզնեսը կարող է շահել։
        ///4.	Կ՞ան արդյոք որոշակի միջոցառումներ, որոնք մեծ հնարավորություններ կնձեռեն։
        ///5.	Կա՞ն արդյոք ոլորտներ, որտեղ Ձեր մրցակիցները խոցելի կլինեն։
        ///6.	Արդյո՞ք սեզոնայնությունը ազդում է Ձեր բիզնեսի վրա։
        ///.
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	ÕÕ¥Ö€ Õ¢Õ«Õ¦Õ¶Õ¥Õ½Õ« Õ¸ÕžÖ€ Õ°Õ¡Õ¿Õ¯Õ¡Õ¶Õ«Õ·Õ¶Õ¥Ö€Õ¶ Õ¸Ö‚Õ¶Õ¥Õ¶ Õ¡Õ¼Õ¡Õ¾Õ¥Õ¬Õ¸Ö‚Õ©ÕµÕ¸Ö‚Õ¶Õ¶Õ¥Ö€ Õ´Ö€ÖÕ¡Õ¯Õ«ÖÕ¶Õ¥Ö€Õ« Õ°Õ¡Õ´Õ¥Õ´Õ¡Õ¿Ö‰
        ///2.	Ô»ÕžÕ¶Õ¹Õ¶ Õ¥Ö„ Õ¤Õ¸Ö‚Ö„ Õ¡Õ¾Õ¥Õ¬Õ« Õ¬Õ¡Õ¾ Õ¡Õ¶Õ¸Ö‚Õ´Ö„Õ¡Õ¶ ÕÕ¥Ö€ Õ´Ö€ÖÕ¡Õ¯Õ«ÖÕ¶Õ¥Ö€Õ¨Ö‰
        ///3.	Ô»ÕžÕ¶Õ¹ Õ¼Õ¥Õ½Õ¸Ö‚Ö€Õ½Õ¶Õ¥Ö€ Õ¸Ö‚Õ¶Õ¥Ö„ Õ¤Õ¸Ö‚Ö„, Õ¸Ö€Õ¸Õ¶Ö„ Ö…Õ£Õ¶Õ¸Ö‚Õ´ Õ¥Õ¶ Õ´Ö€ÖÕ¡Õ¯Õ«ÖÕ¶Õ¥Ö€Õ«Ö Õ¡Õ¼Õ¡Õ» Õ¡Õ¶ÖÕ¶Õ¥Õ¬Ö‰
        ///4.	ÕˆÖ€Õ¸ÕžÕ¶Ö„ Õ¥Õ¶ ÕÕ¥Ö€ Õ¸Ö‚ÕªÕ¥Õ² Õ¯Õ¸Õ²Õ´Õ¥Ö€Õ¨ ÕÕ¥Ö€ Õ´Ö€ÖÕ¡Õ¯Õ«ÖÕ¶Õ¥Ö€Õ« Õ¿Õ¥Õ½Õ¡Õ¶Õ¯ÕµÕ¸Ö‚Õ¶Õ«ÖÖ‰
        ///5.	ÕˆÖ€Õ¸ÕžÕ¶Ö„ Õ¥Õ¶ Õ¨Õ¶Õ¯Õ¥ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	Ո՞ր արտաքին գործոններն են բացասական ազդեցություն թողնում ձեր բիզնեսի վրա։
        ///2.	 Հնարավո՞ր է արդյոք Ձեր մրցակիցների ուժեղ կողմերը Ձեր ընկերության համար լինեն ռիսկային։
        ///3.	Կա՞ն արդյոք որոշակի տեխնոլոգիական կամ այլ փոփոխություններ, որոնք բացասաբար կազդեն Ձեր վաճառքների վրա։
        ///4.	Արդյո՞ք Ձեր ընկերության թույլ կողմերից որևէ մեկը կարող է համարվել պոտենցիալ սպառնալիք:
        ///5.	Արդյո՞ք շուկայում այլ մրցակիցներ են հայտնվել, ի՞նչն են նրանք այլ կերպ անում։
        ///6.	Արդյո՞ք սեզոնայնությունը ազդում է Ձեր բիզնեսի վրա։
        ///.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	Ձեր բիզնեսի ո՞ր հատկանիշներն ունեն թերություններ մրցակիցների համեմատ։
        ///2.	Ի՞նչն եք համարում ձեր հիմնական խոչընդոտները, որոնք թույլ չեն տալիս հասնել նպատակներին։
        ///3.	Ի՞նչը կարող եք բարելավել Ձեր նպատակներին մեկ քայլով մոտենալու համար։
        ///4.	Ուրիշների կարծիքով, որո՞նք են ձեր թույլ կողմերը։
        ///5.	Ի՞նչն է խոչընդոտում Ձեր վաճառքներին։
        ///6.	Արդյո՞ք ընկերության անձնակազմը աշխատանքը բարելավելու համար  մոտիվացիայի կարիք ունի։.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
    }
}
